const types = {
    FETCH_PRODUCTSLIST_REQUEST: 'FETCH_PRODUCTSLIST_REQUEST',
    FETCH_PRODUCTSLIST_SUCCESS: 'FETCH_PRODUCTSLIST_SUCCESS',
    FETCH_PRODUCTSLIST_FAIL: 'FETCH_PRODUCTSLIST_FAIL',
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAIL: 'FETCH_PRODUCT_FAIL'
} 

export default types;