const types = {
    FETCH_PRODUCTSLIST_REQUEST: 'FETCH_PRODUCTSLIST_REQUEST',
    FETCH_PRODUCTSLIST_SUCCESS: 'FETCH_PRODUCTSLIST_SUCCESS',
    FETCH_PRODUCTSLIST_FAIL: 'FETCH_PRODUCTSLIST_FAIL',
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAIL: 'FETCH_PRODUCT_FAIL',
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:  'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL'
} 

export default types;